#+OPTIONS: toc:nil num:nil
#+BEGIN_EXPORT html
---
layout: post
title: "Board Game Reviews"
permalink: /board-game-reviews/
tags: [reviews, board games]
---
#+END_EXPORT
* 7 Wonders Duel
An impressive little game that somehow fits many of the highs of a game of /Civilization/ into a fast-paced 30-minute drafting game. I enjoy the /Pantheon/ expansion for strengthening science and military while adding more interesting choices and effects, but it does make it more thinky and slows things down.

4/5
* Azul
Functions very well as a gateway game for people happy to think strategically, but is a little too cutthroat (low player counts) or random (high player counts). I'm shocked at how terrible I am at it, which probably doesn't help.

3/5
* Baseball Highlights: 2045
Although it's a straightforward deckbuilder, and the strategy and tactics aren't especially deep, the theming is fantastic, and it really captures the feel of a baseball game, especially in the highs late in a close game (or better yet, extra innings). Recommended for baseball fans.

3/5
* Bottom of the 9th
Theming is wonderful, but not much of a game underneath it. Pitching/hitting is matching pennies, and the results are dice rolls. I enjoy some light games, but there's just not enough here for me.

2/5
* Carcassonne
One of the best examples of [[https://magic.wizards.com/en/articles/archive/making-magic/lenticular-design-2014-12-15][lenticular design]]. What starts as a simple tile-laying game evolves as you learn strategies and add the farmers rule to become a delicate dance balancing limited meeples, constant consideration of the lay of the land, opportunistic cooperation, even more opportunistic theft. Base game is great, but the Inns & Cathedrals expansions fills it out a bit with some helpful new tiles and new features that makes roads more valuable and cities have greater risks and rewards.

4/5
* Codenames/Codenames: Duet
A party game acceptable to gamers and non-gamers alike. Incredibly satisfying both as the cluer and the cluee when it works. The original Codenames has some downtime problems for guessers, while Duet can drag if your partner is slow at coming up with clues. Also very easy for new players to break the rules, which can hurt the experience.

3/5
* Ganz schön clever (That's Pretty Clever!)
Accurate name. Roll and write game that is, essentially, Yahtzee if Yahtzee weren't terrible. Getting combos between the different scoring areas feels great, and while there's no direct interaction, turns are short the active player's choices affect the passive player's options, so other people's turns aren't boring.

3/5
* Gloomhaven
Huge, heavy, and unwieldy, and I guess that applies to the game, too, not just the box. Delightfully varied tactical Euro combat. Start with /Jaws of the Lion/, which is much tighter and cheaper and learns from some of this game's mistakes. Quality of life would be a lot lower without the space to leave it out, a playing schedule to justify leaving it out, and the helper application.

5/5
* Gloomhaven: Jaws of the Lion
While it's a bit less crunchy than my personal favorite Spirit Island, Gloomhaven: JOTL offers plenty of tactical combat goodness with the constant tease of the next perk you'll earn, or item you'll get, or cards you'll add to your pool. The hand management and card play systems are stunning, the mostly cooperative formula is brilliant thanks to hidden battle goals, and the classes are fantastic (our novice party member enjoyed the damage of the Hatchet, our veteran was delighted at the Voidwarden's myriad mind control options, and I enjoyed the risky job of protecting them both as the Red Guard; all of us had ample opportunities to shine and help the parties only we could manage, which feels fantastic). The scenario book makes setup a breeze, and I cannot recommend the free Gloomhaven Helper application enough (we use it on a convertible laptop, so everyone can see it and we can interact with the touch screen).

5/5
* Jaipur
Easy to learn but surprisingly deep trading game with meaningful decisions throughout. The short length and randomness from the cards can make luck a factor, but that's not a bad thing.

4/5
* Mage Knight
A stunningly bold roguelike epic told over several hours of exploration, combat, referencing the terrible manuals, and solving delightful optimization puzzles.

5/5
* Pandemic
Although my tastes have gotten a bit heavier since my initial adoration for Pandemic, it still stands up as an accessible, enjoyable, cooperative puzzle I'm happy to bring to the table. It absolutely suffers from quarterbacking, and it can feel a bit samey after a while once you've basically solved the game's core puzzle, but the On the Brink expansion helps with the latter, adding huge variety to the roles and events with some optional modules to spice things up.

4/5
* Pandemic Legacy: Season 1
Board games for me are escapist non-screen entertainment. I especially enjoy tactical gameplay and spending time with friends and loved ones. Pandemic Legacy ruins the clean Pandemic experience by turning it into a bloated, stressful experience with a nonstop barrage of fiddly new rules, a meta arc filled with uncertainty about what you should be focusing on, and a plot that reads like the Spark Notes to a mid-budget disaster film. Midway through, I asked my playing partner if we were having fun, and we weren't. It had become an obligation, and we have enough of those, so we shelved it. I've tried to figure out what exactly I'm missing (even in 2021, this is the number two game /of all time/ on BGG!), and the best I can conjecture is that I have a distaste for experiences where the game declares that bad things happen to you when it's not your fault or it couldn't reasonably be prevented, or even predicted. It may be why something like Marvel Champions appeals to me more than Arkham Horror. But when a Pandemic Legacy game ends with multiple outbreaks and scars from unlucky card draws, I don't come away gushing about emergent narrative and shared experiences, I just come away feeling...bad, and annoyed that I've spent some of my finite gaming time on something that I didn't enjoy. 

2/5
* Patchwork
Somehow equal parts relaxing (it's a polymino game about making a quilt!) and fiercely competitive. Elegant in its simplicity, challenging in its execution, a favorite for head-to-head two-player games.

4/5
* Spirit Island
Spirit Island captures my mind in a way no board game ever has, and only a select few video games have, with every turn an impossible tactical puzzle until a truly inspired combination of powers reveals itself. An utterly brain-burning experience with an embarrassment of riches in terms of content with its expansions. It's both my favorite coop board game and one of the only board games I will happily play solo. My one criticism is that endings are sometimes anticlimactic, though that may also be a sign that the highly customizable difficulty may simply be too low.

5/5
* Sushi Go Party!
My go-to to pull out for non-gamers, but the customizable party version allows both for high replayability and adjustable complexity. It's a very light points-scoring drafting game, but it has legs and it's fun to notice interactions between cards for different menus. Setup is a little slow with having to build the deck every time, which sleeving can help mitigate.

3/5
* Viticulture Essential Edition
A worker placement game elevated by two mechanics I adore: player-chosen turn order, with increasing rewards for later options, and a grande meeple who can take actions whose slots have already been filled. Suffers a good bit from the highly random and swingy visitor cards, some of which are especially unbalanced at high/low player counts (e.g., everyone gives you money, or get victory points for every player who doesn't).

4/5
